### PR TITLE
Add gObjEncoder, fix some encoder bugs

### LINKED ISSUE #69: _optionsFieldName is called twice when generating an encoding using Waargonaut.Generic.gEncoder
When I use `gEncoder` to generate an encoder for a data type, setting an `_optionsFieldName` field name modifier function, that function appears to be called twice, which is a problem if it isn't idempotent. To reproduce:

```haskell
{-# LANGUAGE DataKinds             #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TemplateHaskell       #-}
{-# LANGUAGE TypeFamilies          #-}
module Test where

import Data.Text          (Text)
import Generics.SOP.TH    (deriveGeneric)
import Waargonaut.Encode  (Encoder)
import Waargonaut.Generic (GWaarg, JsonEncode (..), Options (..),
Tagged (..),
                           defaultOpts, gEncoder, untag)

data Foo = Foo
  { abc :: Text
  }
$(deriveGeneric ''Foo)

instance JsonEncode GWaarg Foo where
  mkEncoder = gEncoder (defaultOpts { _optionsFieldName  = tail })

fooEncoder :: Applicative f => Encoder f Foo
fooEncoder = untag (mkEncoder :: Applicative f => Tagged GWaarg
(Encoder f Foo))
```
Now to test in ghci:

```
λ simpleEncodeText fooEncoder (Foo "test")
"{"c":"test"}"
```

I expected to see:
```
λ simpleEncodeText fooEncoder (Foo "test")
"{"bc":"test"}"
```

### PR DESCRIPTION
**Pull request by mankyKitty**
Add `onObj'` which is just `onObj` but specialised to `Identity`.

Add `gObjEncoder` for deriving `ObjEncoder` structures for record types only. Using the
`IsRecord` constraint from `record-sop` package. This makes it easier to leverage the
Contravariant functionality of the `ObjEncoder` without losing the benefits of deriving
more trivial encoders.

Added the `FieldNameAsKey` option to the newtype options for generic derived enc/decoders.

Fixes #69  by removing duplicate call to `_optionsFieldName` function. Added regression
test.

Improved the handling of newtype options for generic deriving to give a bit more
flexibility and avoid strangeness wrt to some combinations of options.

Change the building of escaped whitespace chars to actually use the
`escapedWhitespaceChar` function, instead of incorrectly generating an unescaped
character.

### CODE REVIEW

File: src/Waargonaut/Encode/Builder.hs [hunk 1]
```diff
@@ -35,7 +36,7 @@ textBuilder = Builder
 -- | A 'B.ByteString' builder
 bsBuilder :: Builder ByteString B.Builder
 bsBuilder = Builder
-  B.charUtf8
+  (BP.primBounded BP.charUtf8)-- B.charUtf8
```
Comment (gwils) [inline src/Waargonaut/Encode/Builder.hs]: Is this commented-out code intentional?

File: src/Waargonaut/Generic.hs [hunk 2]
```diff
@@ -53,16 +54,20 @@ module Waargonaut.Generic
...
+import           Generics.SOP.Record (IsRecord)
 
-import           Control.Lens                  (findOf, folded, isn't, _Left)
+import           Control.Lens                  (findOf, folded, isn't, _Left, _Empty, (#))
 import           Control.Monad                 ((>=>))
 import           Control.Monad.Except          (lift, throwError)
 import           Control.Monad.Reader          (runReaderT)
 import           Control.Monad.State           (modify)
 
+import Data.Function ((&))
```
Comment (gwils) [inline src/Waargonaut/Generic.hs]: This line and the foldable import below don't follow your import indentation conventions

File: waargonaut.cabal [hunk 3]
```diff
@@ -10,7 +10,7 @@ name:                waargonaut
 -- PVP summary:      +-+------- breaking API changes
 --                   | | +----- non-breaking API additions
 --                   | | | +--- code changes with no API change
-version:             0.7.0.1
+version:             0.7.1.0
```
Comment (gwils) [inline waargonaut.cabal]: Please make the version `0.8.0.0`. Constructors were added to exported sum types, which is technically a breaking change.

File: src/Waargonaut/Generic.hs [hunk 4]
```diff
@@ -513,6 +523,61 @@ gEncoder opts = Tagged . E.encodeA $ \a -> hcollapse $ hcliftA2
...
+                 -> NP I ys
+                 -> K (f (JObject WS Json)) ys
+    createObject (JsonRec _ fields) cs = K . pure .
+      foldl' (&) (_Empty # ()) . hcollapse $ hcliftA2 pjE toObj fields cs
+
+    createObject (JsonOne (Tag t)) (I a :* Nil) = K . pure $
+      E.onObj' (Text.pack t) (E.asJson' (T.proxy mkEncoder pt) a) E.json (_Empty # ())
+
+    -- IsRecord constraint should make this impossible.
+    createObject _ _ = error "impossible?"
```
Comment (gwils) [inline src/Waargonaut/Generic.hs]: I suggest changing the message to something like.
`"The impossible has happened. Please report this as a waargonaut bug here: https://github.com/qfpl/waargonaut"`
